// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmZ1pC-qCthgrCclRJvzLDIrQub9Zevxo',
    appId: '1:919197197274:android:6e48cdf885e45b2ac656e3',
    messagingSenderId: '919197197274',
    projectId: 'myapplication-b8cee',
    storageBucket: 'myapplication-b8cee.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUdToY4psPZW3rtlELMhIbePYTHj5sKwA',
    appId: '1:919197197274:web:2593691b1964596ac656e3',
    messagingSenderId: '919197197274',
    projectId: 'myapplication-b8cee',
    authDomain: 'myapplication-b8cee.firebaseapp.com',
    storageBucket: 'myapplication-b8cee.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAWtSsX9S4QDP85YgU9X3Jj-XLQ4E6STU',
    appId: '1:919197197274:ios:9c79172b4978808fc656e3',
    messagingSenderId: '919197197274',
    projectId: 'myapplication-b8cee',
    storageBucket: 'myapplication-b8cee.firebasestorage.app',
    iosBundleId: 'com.example.pandey',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAWtSsX9S4QDP85YgU9X3Jj-XLQ4E6STU',
    appId: '1:919197197274:ios:9c79172b4978808fc656e3',
    messagingSenderId: '919197197274',
    projectId: 'myapplication-b8cee',
    storageBucket: 'myapplication-b8cee.firebasestorage.app',
    iosBundleId: 'com.example.pandey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUdToY4psPZW3rtlELMhIbePYTHj5sKwA',
    appId: '1:919197197274:web:a3798200754f4146c656e3',
    messagingSenderId: '919197197274',
    projectId: 'myapplication-b8cee',
    authDomain: 'myapplication-b8cee.firebaseapp.com',
    storageBucket: 'myapplication-b8cee.firebasestorage.app',
  );
}
