import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:dio/dio.dart';
import 'lgd_villages_state.dart';

class LgdVillagesCubit extends Cubit<LgdVillagesState> {
  final Dio _dio;

  LgdVillagesCubit({Dio? dio})
      : _dio = dio ?? Dio(),
        super(LgdVillagesInitial());

  static const String apiKey = '579b464db66ec23bdd000001cdd3946e44ce4aad7209ff7b23ac571b';
  // Standard LGD Village directory dataset resource ID on data.gov.in
  static const String resourceId = '12e987c6-302a-436f-870c-26d97c36a3d0';
  static const String apiUrl = 'https://api.data.gov.in/resource/$resourceId?api-key=$apiKey&format=json&filters[district_name]=Siddharthnagar&limit=100';

  final List<LgdVillageModel> _fallbackVillages = const [
    // Naugarh Block
    LgdVillageModel(
      villageCode: '181234',
      villageNameEnglish: 'Naugarh',
      villageNameLocal: 'नौगढ़',
      blockName: 'Naugarh',
      gramPanchayatName: 'Naugarh GP',
      tehsilName: 'Naugarh',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272207',
    ),
    LgdVillageModel(
      villageCode: '181235',
      villageNameEnglish: 'Birdpur No. 1',
      villageNameLocal: 'बर्डपुर नंबर 1',
      blockName: 'Birdpur',
      gramPanchayatName: 'Birdpur GP',
      tehsilName: 'Naugarh',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272202',
    ),
    LgdVillageModel(
      villageCode: '181236',
      villageNameEnglish: 'Jogia',
      villageNameLocal: 'जोगिया',
      blockName: 'Jogia',
      gramPanchayatName: 'Jogia GP',
      tehsilName: 'Naugarh',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272207',
    ),
    LgdVillageModel(
      villageCode: '181237',
      villageNameEnglish: 'Kakrahi',
      villageNameLocal: 'ककराही',
      blockName: 'Naugarh',
      gramPanchayatName: 'Kakrahi GP',
      tehsilName: 'Naugarh',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272207',
    ),
    LgdVillageModel(
      villageCode: '181238',
      villageNameEnglish: 'Bariji',
      villageNameLocal: 'बारीजी',
      blockName: 'Birdpur',
      gramPanchayatName: 'Bariji GP',
      tehsilName: 'Naugarh',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272202',
    ),
    LgdVillageModel(
      villageCode: '181239',
      villageNameEnglish: 'Nankar',
      villageNameLocal: 'नानकार',
      blockName: 'Jogia',
      gramPanchayatName: 'Nankar GP',
      tehsilName: 'Naugarh',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272207',
    ),
    LgdVillageModel(
      villageCode: '181240',
      villageNameEnglish: 'Madhubani',
      villageNameLocal: 'मधुबनी',
      blockName: 'Naugarh',
      gramPanchayatName: 'Madhubani GP',
      tehsilName: 'Naugarh',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272207',
    ),
    LgdVillageModel(
      villageCode: '181241',
      villageNameEnglish: 'Pipra',
      villageNameLocal: 'पिपरा',
      blockName: 'Uska Bazar',
      gramPanchayatName: 'Pipra GP',
      tehsilName: 'Naugarh',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272206',
    ),
    LgdVillageModel(
      villageCode: '181242',
      villageNameEnglish: 'Hathivera',
      villageNameLocal: 'हाथीवेरा',
      blockName: 'Naugarh',
      gramPanchayatName: 'Hathivera GP',
      tehsilName: 'Naugarh',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272207',
    ),
    LgdVillageModel(
      villageCode: '181243',
      villageNameEnglish: 'Katya',
      villageNameLocal: 'काट्या',
      blockName: 'Birdpur',
      gramPanchayatName: 'Katya GP',
      tehsilName: 'Naugarh',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272202',
    ),

    // Bansi Block
    LgdVillageModel(
      villageCode: '181244',
      villageNameEnglish: 'Bansi Dehat',
      villageNameLocal: 'बांसी देहात',
      blockName: 'Bansi',
      gramPanchayatName: 'Bansi GP',
      tehsilName: 'Bansi',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272153',
    ),
    LgdVillageModel(
      villageCode: '181245',
      villageNameEnglish: 'Lalpur',
      villageNameLocal: 'लालपुर',
      blockName: 'Bansi',
      gramPanchayatName: 'Lalpur GP',
      tehsilName: 'Bansi',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272153',
    ),
    LgdVillageModel(
      villageCode: '181246',
      villageNameEnglish: 'Khesraha Rural',
      villageNameLocal: 'खेसरहा ग्रामीण',
      blockName: 'Khesraha',
      gramPanchayatName: 'Khesraha GP',
      tehsilName: 'Bansi',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272152',
    ),
    LgdVillageModel(
      villageCode: '181247',
      villageNameEnglish: 'Semra',
      villageNameLocal: 'सेमरा',
      blockName: 'Bansi',
      gramPanchayatName: 'Semra GP',
      tehsilName: 'Bansi',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272153',
    ),
    LgdVillageModel(
      villageCode: '181248',
      villageNameEnglish: 'Chandee',
      villageNameLocal: 'चंडी',
      blockName: 'Khesraha',
      gramPanchayatName: 'Chandee GP',
      tehsilName: 'Bansi',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272152',
    ),
    LgdVillageModel(
      villageCode: '181249',
      villageNameEnglish: 'Patar',
      villageNameLocal: 'पातर',
      blockName: 'Bansi',
      gramPanchayatName: 'Patar GP',
      tehsilName: 'Bansi',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272153',
    ),
    LgdVillageModel(
      villageCode: '181250',
      villageNameEnglish: 'Bitharia',
      villageNameLocal: 'बिथरिया',
      blockName: 'Bansi',
      gramPanchayatName: 'Bitharia GP',
      tehsilName: 'Bansi',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272153',
    ),
    LgdVillageModel(
      villageCode: '181251',
      villageNameEnglish: 'Parsa',
      villageNameLocal: 'परसा',
      blockName: 'Khesraha',
      gramPanchayatName: 'Parsa GP',
      tehsilName: 'Bansi',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272152',
    ),
    LgdVillageModel(
      villageCode: '181252',
      villageNameEnglish: 'Belwa Khas',
      villageNameLocal: 'बेलवा खास',
      blockName: 'Bansi',
      gramPanchayatName: 'Belwa GP',
      tehsilName: 'Bansi',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272153',
    ),
    LgdVillageModel(
      villageCode: '181253',
      villageNameEnglish: 'Sewa',
      villageNameLocal: 'सेवा',
      blockName: 'Bansi',
      gramPanchayatName: 'Sewa GP',
      tehsilName: 'Bansi',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272153',
    ),

    // Shohratgarh Block
    LgdVillageModel(
      villageCode: '181254',
      villageNameEnglish: 'Shohratgarh Dehat',
      villageNameLocal: 'शोहरतगढ़ देहात',
      blockName: 'Shohratgarh',
      gramPanchayatName: 'Shohratgarh GP',
      tehsilName: 'Shohratgarh',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272205',
    ),
    LgdVillageModel(
      villageCode: '181255',
      villageNameEnglish: 'Khairati',
      villageNameLocal: 'खैराती',
      blockName: 'Shohratgarh',
      gramPanchayatName: 'Khairati GP',
      tehsilName: 'Shohratgarh',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272205',
    ),
    LgdVillageModel(
      villageCode: '181256',
      villageNameEnglish: 'Mudila',
      villageNameLocal: 'मुदिला',
      blockName: 'Shohratgarh',
      gramPanchayatName: 'Mudila GP',
      tehsilName: 'Shohratgarh',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272205',
    ),
    LgdVillageModel(
      villageCode: '181257',
      villageNameEnglish: 'Mahdeva',
      villageNameLocal: 'महादेवा',
      blockName: 'Shohratgarh',
      gramPanchayatName: 'Mahdeva GP',
      tehsilName: 'Shohratgarh',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272205',
    ),
    LgdVillageModel(
      villageCode: '181258',
      villageNameEnglish: 'Talpur',
      villageNameLocal: 'तालपुर',
      blockName: 'Shohratgarh',
      gramPanchayatName: 'Talpur GP',
      tehsilName: 'Shohratgarh',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272205',
    ),
    LgdVillageModel(
      villageCode: '181259',
      villageNameEnglish: 'Kalyanpur',
      villageNameLocal: 'कल्याणपुर',
      blockName: 'Shohratgarh',
      gramPanchayatName: 'Kalyanpur GP',
      tehsilName: 'Shohratgarh',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272205',
    ),
    LgdVillageModel(
      villageCode: '181260',
      villageNameEnglish: 'Barhni Dehat',
      villageNameLocal: 'बढ़नी देहात',
      blockName: 'Barhni',
      gramPanchayatName: 'Barhni GP',
      tehsilName: 'Shohratgarh',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272201',
    ),
    LgdVillageModel(
      villageCode: '181261',
      villageNameEnglish: 'Lohra',
      villageNameLocal: 'लोहरा',
      blockName: 'Shohratgarh',
      gramPanchayatName: 'Lohra GP',
      tehsilName: 'Shohratgarh',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272205',
    ),
    LgdVillageModel(
      villageCode: '181262',
      villageNameEnglish: 'Persia',
      villageNameLocal: 'पर्सिया',
      blockName: 'Shohratgarh',
      gramPanchayatName: 'Persia GP',
      tehsilName: 'Shohratgarh',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272205',
    ),
    LgdVillageModel(
      villageCode: '181263',
      villageNameEnglish: 'Ramnagar',
      villageNameLocal: 'रामनगर',
      blockName: 'Barhni',
      gramPanchayatName: 'Ramnagar GP',
      tehsilName: 'Shohratgarh',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272201',
    ),

    // Itwa Block
    LgdVillageModel(
      villageCode: '181264',
      villageNameEnglish: 'Itwa Dehat',
      villageNameLocal: 'इटवा देहात',
      blockName: 'Itwa',
      gramPanchayatName: 'Itwa GP',
      tehsilName: 'Itwa',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272192',
    ),
    LgdVillageModel(
      villageCode: '181265',
      villageNameEnglish: 'Trilokpur',
      villageNameLocal: 'त्रिलोकपुर',
      blockName: 'Itwa',
      gramPanchayatName: 'Trilokpur GP',
      tehsilName: 'Itwa',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272192',
    ),
    LgdVillageModel(
      villageCode: '181266',
      villageNameEnglish: 'Khuniyaon Dehat',
      villageNameLocal: 'खुनियांव देहात',
      blockName: 'Khuniyaon',
      gramPanchayatName: 'Khuniyaon GP',
      tehsilName: 'Itwa',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272192',
    ),
    LgdVillageModel(
      villageCode: '181267',
      villageNameEnglish: 'Misrauli',
      villageNameLocal: 'मिसरौली',
      blockName: 'Itwa',
      gramPanchayatName: 'Misrauli GP',
      tehsilName: 'Itwa',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272192',
    ),
    LgdVillageModel(
      villageCode: '181268',
      villageNameEnglish: 'Ganeshpur',
      villageNameLocal: 'गणेशपुर',
      blockName: 'Khuniyaon',
      gramPanchayatName: 'Ganeshpur GP',
      tehsilName: 'Itwa',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272192',
    ),
    LgdVillageModel(
      villageCode: '181269',
      villageNameEnglish: 'Bhadar',
      villageNameLocal: 'भादर',
      blockName: 'Itwa',
      gramPanchayatName: 'Bhadar GP',
      tehsilName: 'Itwa',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272192',
    ),
    LgdVillageModel(
      villageCode: '181270',
      villageNameEnglish: 'Gaur',
      villageNameLocal: 'गौर',
      blockName: 'Itwa',
      gramPanchayatName: 'Gaur GP',
      tehsilName: 'Itwa',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272192',
    ),
    LgdVillageModel(
      villageCode: '181271',
      villageNameEnglish: 'Lachhmanpur',
      villageNameLocal: 'लक्ष्मणपुर',
      blockName: 'Khuniyaon',
      gramPanchayatName: 'Lachhmanpur GP',
      tehsilName: 'Itwa',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272192',
    ),
    LgdVillageModel(
      villageCode: '181272',
      villageNameEnglish: 'Pachperwa',
      villageNameLocal: 'पचपेड़वा',
      blockName: 'Itwa',
      gramPanchayatName: 'Pachperwa GP',
      tehsilName: 'Itwa',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272192',
    ),
    LgdVillageModel(
      villageCode: '181273',
      villageNameEnglish: 'Dhanora',
      villageNameLocal: 'धनोरा',
      blockName: 'Itwa',
      gramPanchayatName: 'Dhanora GP',
      tehsilName: 'Itwa',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272192',
    ),

    // Domariaganj Block
    LgdVillageModel(
      villageCode: '181274',
      villageNameEnglish: 'Domariaganj Dehat',
      villageNameLocal: 'डुमरियागंज देहात',
      blockName: 'Dumariyaganj',
      gramPanchayatName: 'Domariaganj GP',
      tehsilName: 'Domariaganj',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272189',
    ),
    LgdVillageModel(
      villageCode: '181275',
      villageNameEnglish: 'Bharatpur',
      villageNameLocal: 'भरतपुर',
      blockName: 'Dumariyaganj',
      gramPanchayatName: 'Bharatpur GP',
      tehsilName: 'Domariaganj',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272189',
    ),
    LgdVillageModel(
      villageCode: '181276',
      villageNameEnglish: 'Bhanwapur Dehat',
      villageNameLocal: 'भानवापुर देहात',
      blockName: 'Bhanwapur',
      gramPanchayatName: 'Bhanwapur GP',
      tehsilName: 'Domariaganj',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272189',
    ),
    LgdVillageModel(
      villageCode: '181277',
      villageNameEnglish: 'Pipra Ram',
      villageNameLocal: 'पिपरा राम',
      blockName: 'Dumariyaganj',
      gramPanchayatName: 'Pipra Ram GP',
      tehsilName: 'Domariaganj',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272189',
    ),
    LgdVillageModel(
      villageCode: '181278',
      villageNameEnglish: 'Hallaur',
      villageNameLocal: 'हल्लौर',
      blockName: 'Dumariyaganj',
      gramPanchayatName: 'Hallaur GP',
      tehsilName: 'Domariaganj',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272191',
    ),
    LgdVillageModel(
      villageCode: '181279',
      villageNameEnglish: 'Bhadaria',
      villageNameLocal: 'भदारिया',
      blockName: 'Bhanwapur',
      gramPanchayatName: 'Bhadaria GP',
      tehsilName: 'Domariaganj',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272189',
    ),
    LgdVillageModel(
      villageCode: '181280',
      villageNameEnglish: 'Sikandra',
      villageNameLocal: 'सिकंद्रा',
      blockName: 'Dumariyaganj',
      gramPanchayatName: 'Sikandra GP',
      tehsilName: 'Domariaganj',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272189',
    ),
    LgdVillageModel(
      villageCode: '181281',
      villageNameEnglish: 'Turkaulia',
      villageNameLocal: 'तुरकौलिया',
      blockName: 'Dumariyaganj',
      gramPanchayatName: 'Turkaulia GP',
      tehsilName: 'Domariaganj',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272189',
    ),
    LgdVillageModel(
      villageCode: '181282',
      villageNameEnglish: 'Jigna',
      villageNameLocal: 'जिग्ना',
      blockName: 'Bhanwapur',
      gramPanchayatName: 'Jigna GP',
      tehsilName: 'Domariaganj',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272189',
    ),
    LgdVillageModel(
      villageCode: '181283',
      villageNameEnglish: 'Mahua Khas',
      villageNameLocal: 'महुआ खास',
      blockName: 'Dumariyaganj',
      gramPanchayatName: 'Mahua GP',
      tehsilName: 'Domariaganj',
      districtName: 'Siddharthnagar',
      stateName: 'Uttar Pradesh',
      pincode: '272189',
    ),
  ];

  Future<void> fetchVillages() async {
    emit(LgdVillagesLoading());
    try {
      final response = await _dio.get(apiUrl);
      if (response.statusCode == 200 && response.data != null) {
        final data = response.data;
        if (data is Map<String, dynamic> && data.containsKey('records')) {
          final List<dynamic> records = data['records'];
          final List<LgdVillageModel> list = records
              .map((json) => LgdVillageModel.fromJson(json as Map<String, dynamic>))
              .toList();

          if (list.isEmpty) {
            emit(LgdVillagesSuccess(villages: _fallbackVillages, isLive: false));
          } else {
            emit(LgdVillagesSuccess(villages: list, isLive: true));
          }
        } else {
          emit(LgdVillagesSuccess(villages: _fallbackVillages, isLive: false));
        }
      } else {
        emit(LgdVillagesSuccess(villages: _fallbackVillages, isLive: false));
      }
    } catch (_) {
      emit(LgdVillagesSuccess(villages: _fallbackVillages, isLive: false));
    }
  }
}
